#!/bin/sh

function error() {
  echo -e "[ERROR] " $1
  exit 1
}

function info() {
  echo -e "[INFO] " $1
}

if [ ! `builtin command -v brew` ]; then
  error 'Install homebrew before executing this install script.'
fi

# tpm
info 'Install tpm'
if [ ! -e $HOME/.tmux/plugins/tpm ]; then
  info 'Install tpm'
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
else
  info 'tpm is already installed' 
fi

# monaco nerd fonts
info 'Install monaco nerd fonts'
if [ ! -d $HOME/git/monaco-nerd-fonts ]; then
  info 'Install monaco-nerd-fonts'
  git clone https://github.com/Karmenzind/monaco-nerd-fonts.git $HOME/git/monaco-nerd-fonts
  cp $HOME/git/monaco-nerd-fonts/fonts/* $HOME/Library/fonts
else
  info 'monaco nerd fonts are already installed' 
fi

# brew
info 'Install homebrew formulae'
brew install go \
  tig \
  fzf \
  tmux \
  starship \
  zsh-autosuggestions \
  gsed \
  kubectl \
  direnv \
  htop \
  fontconfig \
  git-extras \
  yarn \
  tree \
  fd \
  jq \
  ctags \
  direnv \
  ripgrep \
  ninja \
  nkf \
  git \
  alacritty

brew tap homebrew/cask-fonts
brew install --cask font-hack-nerd-font
# brew install --HEAD neovim
brew install neovim

info 'Install fzf'
if [ ! -e $HOME/.fzf.zsh ]; then
  info 'Install fzf'
  $(brew --prefix)/opt/fzf/install
else
  info 'fzf is already installed' 
fi

# Language server
info 'Install Language servers'
yarn global add bash-language-server typescript typescript-language-server vim-language-server

# zsh
info 'Install .zshrc'
if [ ! -h $HOME/.zshrc ]; then
  echo '=> ln -sn $HOME/git/dotfiles/zshrc $HOME/.zshrc'
  ln -sn $HOME/git/dotfiles/zshrc $HOME/.zshrc
else
  info '.zshrc is already installed' 
fi

# tmux 
info 'Install .tmux.conf'
if [ ! -h $HOME/.tmux.conf ]; then
  echo '=> ln -sn $HOME/git/dotfiles/tmux.conf $HOME/.tmux.conf'
  ln -sn $HOME/git/dotfiles/tmux.conf $HOME/.tmux.conf
else
  info '.tmux.conf is already installed' 
fi

# nvim
info 'Install nvim configurations'
if [ ! -h $HOME/.config/nvim ]; then
  echo '=> ln -sn $HOME/git/dotfiles/nvim $HOME/.config/nvim'
  ln -sn $HOME/git/dotfiles/nvim $HOME/.config/nvim
else
  info 'nvim configurations is already installed' 
fi

# tig
info 'Install .tigrc'
if [ ! -h $HOME/.tigrc ]; then
  echo '=> ln -sn $HOME/git/dotfiles/tigrc $HOME/.tigrc'
  ln -sn $HOME/git/dotfiles/tigrc $HOME/.tigrc
else
  info '.tigrc is already installed' 
fi

# gitcoinfg
info 'Install git configurations'
if [ ! -h $HOME/.gitconfig ]; then
  echo '=> ln -sn $HOME/git/dotfiles/gitconfig $HOME/git/.gitconfig'
  ln -sn $HOME/git/dotfiles/gitconfig $HOME/.gitconfig
else
  info '$HOME/.gitconfig is already installed' 
fi
if [ ! -h $HOME/git/private/gitconfig ]; then
  mkdir -p $HOME/git/private
  echo '=> ln -sn $HOME/git/dotfiles/gitconfig $HOME/git/private/gitconfig'
  ln -sn $HOME/git/dotfiles/gitconfig-private $HOME/git/private/gitconfig
else
  info '$HOME/git/private/gitconfig is already installed' 
fi

# starship
info 'Install starship.toml'
if [ ! -h $HOME/.config/starship.toml ]; then
  mkdir -p $HOME/.config
  echo '=> ln -sn $HOME/git/dotfiles/starship.toml $HOME/.config/starship.toml'
  ln -sn $HOME/git/dotfiles/starship.toml $HOME/.config/starship.toml
else
  info 'starship.toml is already installed' 
fi

# starship
info 'Install taplo.toml'
if [ ! -h $HOME/.taplo.toml ]; then
  echo '=> ln -sn $HOME/git/dotfiles/taplo.toml $HOME/.taplo.toml'
  ln -sn $HOME/git/dotfiles/taplo.toml $HOME/.taplo.toml
else
  info 'taplo.toml is already installed' 
fi


# gopls
info 'Install gopls' 
go install golang.org/x/tools/gopls@latest

# go tools
info 'Install goimports'
go install golang.org/x/tools/cmd/goimports@latest

# Lua Langualge Server
if [ ! -d $HOME/git/lua-language-server ]; then
  git clone https://github.com/sumneko/lua-language-server $HOME/git/lua-language-server
  cd $HOME/git/lua-language-server
  git submodule update --init --recursive

  cd 3rd/luamake
  compile/install.sh
  cd ../..
  ./3rd/luamake/luamake rebuild
fi

# Alacritty
info 'Install Alacritty configurations'
if [ ! -h $HOME/.alacritty.toml ]; then
  echo '=> ln -sn $HOME/git/dotfiles/alacritty.toml $HOME/.alacritty.toml'
  ln -sn $HOME/git/dotfiles/alacritty.toml $HOME/.alacritty.toml
else
  info 'Alacritty configurations is already installed' 
fi
