#!/bin/sh

# zsh
if [ ! -h $HOME/.zshrc ]; then
    echo '=> ln -sn $HOME/git/dotfiles/zshrc $HOME/.zshrc'
    ln -sn $HOME/git/dotfiles/zshrc $HOME/.zshrc
fi

# tmux 
if [ ! -h $HOME/.tmux.conf ]; then
    echo '=> ln -sn $HOME/git/dotfiles/tmux.conf $HOME/.tmux.conf'
    ln -sn $HOME/git/dotfiles/tmux.conf $HOME/.tmux.conf
fi

# vim
if [ ! -h $HOME/.vimrc ]; then
    echo '=> ln -sn $HOME/git/dotfiles/vimrc $HOME/.vimrc'
    ln -sn $HOME/git/dotfiles/vimrc $HOME/.vimrc
fi

# nvim
if [ ! -h $HOME/.config/nvim/init.vim ]; then
    echo '=> mkdir -p $HOME/.config/nvim'
    mkdir -p $HOME/.config/nvim
    echo '=> ln -sn $HOME/git/dotfiles/nvim/init.vim $HOME/.config/nvim/init.vim'
    ln -sn $HOME/git/dotfiles/nvim/init.vim $HOME/.config/nvim/init.vim
fi

if [ ! -d $HOME/.config/nvim/settings ]; then
    echo '=> mkdir -p $HOME/.config/nvim/settings'
    mkdir -p $HOME/.config/nvim/settings
fi

if [ ! -h $HOME/.config/nvim/settings/mappings.vim ]; then
    echo '=> ln -sn $HOME/git/dotfiles/nvim/settings/mappings.vim $HOME/.config/nvim/settings/mappings.vim'
    ln -sn $HOME/git/dotfiles/nvim/settings/mappings.vim $HOME/.config/nvim/settings/mappings.vim
fi

if [ ! -h $HOME/.config/nvim/settings/options.vim ]; then
    echo '=> ln -sn $HOME/git/dotfiles/nvim/settings/options.vim $HOME/.config/nvim/settings/options.vim'
    ln -sn $HOME/git/dotfiles/nvim/settings/options.vim $HOME/.config/nvim/settings/options.vim
fi

# tig
if [ ! -h $HOME/.tigrc ]; then
    echo '=> ln -sn $HOME/git/dotfiles/tigrc $HOME/.tigrc'
    ln -sn $HOME/git/dotfiles/tigrc $HOME/.tigrc
fi

# peco
if [ ! -d $HOME/.peco ]; then
    echo '=> ln -sn $HOME/git/dotfiles/peco $HOME/.peco'
    ln -sn $HOME/git/dotfiles/peco $HOME/.peco
fi

# gitcoinfg
if [ ! -h $HOME/private/gitconfig ]; then
    mkdir -p $HOME/private
    echo '=> ln -sn $HOME/git/dotfiles/gitconfig $HOME/private/gitconfig'
    ln -sn $HOME/git/dotfiles/gitconfig $HOME/private/gitconfig
fi
