[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

[[plugins]]
repo = 'majutsushi/tagbar'
on_ft = ['go']

[[plugins]]
repo = 'zchee/deoplete-go'
on_ft = ['go']
build = 'make'

[[plugins]]
repo = 'junegunn/fzf.vim'
on_ft = ['go']
depends = 'fzf'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = 0
